from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, ForeignKey, UniqueConstraint, Numeric, Index, Date, LargeBinary, Time
from sqlalchemy.dialects.postgresql import JSONB, DOUBLE_PRECISION
from datetime import datetime
from src.infrastructure.database import Base

class ShopOrderChannel(Base):
    __tablename__ = "shop_master_order_channels"
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False)
    order_channel_type = Column(String(128))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopOrderPaymentType(Base):
    __tablename__ = "shop_master_order_payment_types"
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopOrderStatus(Base):
    __tablename__ = "shop_master_order_statuses"
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False)
    order_status_type = Column(String(128))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopProductCategory(Base):
    __tablename__ = "shop_product_categories"
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False)
    description = Column(Text)
    public_url = Column(String(512))
    meta_keywords = Column(String(1024))
    icon = Column(String)
    image_url = Column(String(512))
    draft_or_published = Column(String(128))
    display_sequence = Column(Integer)
    category_manager_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopImageVideoLibrary(Base):
    __tablename__ = "shop_image_video_libraries"
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False)
    description = Column(Text)
    video_or_image = Column(String(50), default='image')
    internal_url = Column(String(512))
    external_url = Column(String(512))
    original_name = Column(String(256))
    size = Column(String(128))
    file_extension = Column(String(128))
    dimension = Column(String(128))
    seo_tag = Column(String(256))
    create_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopStoreType(Base):
    __tablename__ = "shop_master_store_type"
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopStore(Base):
    __tablename__ = "shop_stores"
    id = Column(Integer, primary_key=True)
    name = Column(String(1024), nullable=False)
    store_public_url = Column(String(1024))
    store_short_description = Column(Text)
    description = Column(Text)
    logo = Column(String)
    seo_tag = Column(String(512))
    full_address = Column(String(2048))
    address = Column(String(1024))
    city = Column(String(128))
    zip_code = Column(String(50))
    latitude = Column(Numeric)
    longitude = Column(Numeric)
    phone = Column(String(50))
    fax = Column(String(128))
    mobile = Column(String(50))
    email = Column(String(256))
    draft_or_published = Column(String(128))
    facebook = Column(String(1024))
    instagram = Column(String(1024))
    website = Column(String(1024))
    year_of_establishment = Column(String(128))
    display_sequence = Column(Integer)
    physical_store_or_online_store = Column(Boolean, default=False)
    verified = Column(Boolean, default=False)
    store_snapshot_json = Column(JSONB)
    store_snapshot_json_url = Column(String(2048))
    snapshot_generated_at = Column(DateTime)
    rating_score = Column(Integer)
    store_type_id = Column(Integer, ForeignKey("shop_master_store_type.id"))
    store_manager_user_id = Column(Integer, ForeignKey("app_users.id"))
    master_hub_id = Column(Integer)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopProduct(Base):
    __tablename__ = "shop_products"
    id = Column(Integer, primary_key=True)
    name = Column(String(1024), nullable=False)
    short_description = Column(Text)
    primary_image = Column(Text)
    description = Column(Text)
    sku = Column(String(256))
    public_url = Column(String(1024))
    seo_keywords = Column(String(1024))
    regular_price = Column(DOUBLE_PRECISION)
    sale_price = Column(DOUBLE_PRECISION)
    discount_percentage = Column(DOUBLE_PRECISION)
    discount_amount = Column(DOUBLE_PRECISION)
    call_for_price = Column(Boolean, default=False)
    unit_price = Column(DOUBLE_PRECISION)
    tax_exempt = Column(Boolean, default=False)
    stock_quantity = Column(Integer)
    display_stock_quantity = Column(Boolean, default=False)
    draft_or_published = Column(String(128))
    package_product = Column(Boolean, default=False)
    internal_notes = Column(Text)
    save_as_template = Column(Boolean, default=False)
    product_or_service = Column(Boolean, default=False)
    verified = Column(Boolean, default=False)
    product_snapshot_json = Column(JSONB)
    product_snapshot_json_url = Column(String(2048))
    snapshot_generated_at = Column(DateTime)
    rating_score = Column(Integer)
    product_category_id = Column(Integer, ForeignKey("shop_product_categories.id"))
    master_currency_id = Column(Integer)
    store_id = Column(Integer, ForeignKey("shop_stores.id"))
    product_manager_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopOrder(Base):
    __tablename__ = "shop_orders"
    id = Column(Integer, primary_key=True)
    order_number = Column(String(256), nullable=False)
    order_date = Column(DateTime)
    service_or_product = Column(Boolean, default=True)
    delivery_or_pickup = Column(Boolean, default=False)
    payment_completed = Column(Boolean, default=False)
    full_name = Column(String(512))
    street_address = Column(String(512))
    city = Column(String(128))
    zip_code = Column(String(128))
    email = Column(String(256))
    phone = Column(String(50))
    customer_notes = Column(String(5000))
    total_discount_amount = Column(DOUBLE_PRECISION)
    service_charge = Column(DOUBLE_PRECISION)
    number_of_items = Column(Integer)
    sub_total_excluded_tax = Column(DOUBLE_PRECISION)
    total_tax_amount = Column(DOUBLE_PRECISION)
    discount_code_id = Column(Integer)
    zone_id = Column(Integer)
    master_country_id = Column(Integer)
    shop_order_status_type_id = Column(Integer, ForeignKey("shop_master_order_statuses.id"))
    shop_order_channel_type_id = Column(Integer, ForeignKey("shop_master_order_channels.id"))
    user_id = Column(Integer, ForeignKey("app_users.id"))
    shop_order_status = Column(String(50), default='Processing')
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopOrderDetail(Base):
    __tablename__ = "shop_order_details"
    id = Column(Integer, primary_key=True)
    quantity = Column(Integer)
    unit_price = Column(DOUBLE_PRECISION)
    discount_percentage_by_item = Column(DOUBLE_PRECISION)
    discount_amount_by_item = Column(DOUBLE_PRECISION)
    total_amount_by_item = Column(DOUBLE_PRECISION)
    shop_order_id = Column(Integer, ForeignKey("shop_orders.id"))
    shop_product_id = Column(Integer, ForeignKey("shop_products.id"))
    user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopOrderPayment(Base):
    __tablename__ = "shop_order_payments"
    id = Column(Integer, primary_key=True)
    payment_date = Column(DateTime)
    payment_time = Column(String(128))
    payment_split = Column(Boolean, default=False)
    pay_split_amount = Column(DOUBLE_PRECISION)
    due_amount = Column(DOUBLE_PRECISION)
    save_credit_card_number = Column(Boolean, default=False)
    masked_credit_card_number = Column(Text)
    card_name = Column(String(256))
    card_number = Column(String(128))
    card_cvv = Column(String(50))
    card_expiration_month = Column(String(128))
    card_expiration_year = Column(String(128))
    billing_address = Column(String(1024))
    billing_city = Column(String(128))
    billing_state = Column(String(128))
    billing_zip_code = Column(String(128))
    authorization_transaction_number = Column(Text)
    authorization_transaction_code = Column(Text)
    authorization_transaction_result = Column(Text)
    customer_ip_address = Column(Text)
    customer_device_info = Column(Text)
    shop_order_id = Column(Integer, ForeignKey("shop_orders.id"))
    shop_order_payment_type_id = Column(Integer, ForeignKey("shop_master_order_payment_types.id"))
    shop_order_payment_status_id = Column(Integer)
    created_by = Column(Integer, ForeignKey("app_users.id"))
    updated_by = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopShoppingCart(Base):
    __tablename__ = "shop_shopping_carts"
    id = Column(Integer, primary_key=True)
    save_cart_name = Column(String(256))
    unit_price = Column(DOUBLE_PRECISION)
    quantity = Column(Integer)
    unit_discount_amount = Column(DOUBLE_PRECISION)
    unit_total_price = Column(DOUBLE_PRECISION)
    total_amount = Column(DOUBLE_PRECISION)
    ordered_or_removed = Column(Boolean, default=False)
    user_id = Column(Integer, ForeignKey("app_users.id"))
    shop_product_id = Column(Integer, ForeignKey("shop_products.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopDiscountCode(Base):
    __tablename__ = "shop_discount_codes"
    id = Column(Integer, primary_key=True)
    name = Column(String(256), nullable=False)
    coupon_code = Column(String(128))
    percentage_or_fixed_amount = Column(DOUBLE_PRECISION)
    discount_percentage = Column(DOUBLE_PRECISION)
    discount_amount = Column(DOUBLE_PRECISION)
    start_date = Column(DateTime)
    end_date = Column(DateTime)
    start_time = Column(String(128))
    end_time = Column(String(128))
    active_or_expired = Column(Boolean, default=True)
    admin_notes = Column(String(1500))
    shop_store_id = Column(Integer, ForeignKey("shop_stores.id"))
    shop_product_id = Column(Integer, ForeignKey("shop_products.id"))
    shop_order_id = Column(Integer, ForeignKey("shop_orders.id"))
    created_by = Column(Integer, ForeignKey("app_users.id"))
    updated_by = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopProductReview(Base):
    __tablename__ = "shop_product_reviews"
    id = Column(Integer, primary_key=True)
    rating = Column(Integer, nullable=False)
    review_title = Column(String(256))
    review_content = Column(Text)
    is_verified_purchase = Column(Boolean, default=False)
    published = Column(Boolean, default=True)
    shop_product_id = Column(Integer, ForeignKey("shop_products.id"), nullable=False)
    shop_store_id = Column(Integer, ForeignKey("shop_stores.id"), nullable=False)
    shop_order_id = Column(Integer, ForeignKey("shop_orders.id"))
    user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopOrderReturn(Base):
    __tablename__ = "shop_order_returns"
    id = Column(Integer, primary_key=True)
    return_reason = Column(String(256), nullable=False)
    return_status = Column(String(50), default='Requested')
    admin_notes = Column(Text)
    customer_notes = Column(Text)
    refund_amount = Column(DOUBLE_PRECISION)
    shop_order_id = Column(Integer, ForeignKey("shop_orders.id"), nullable=False)
    shop_order_detail_id = Column(Integer, ForeignKey("shop_order_details.id"))
    user_id = Column(Integer, ForeignKey("app_users.id"))
    processed_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    shop_store_id = Column(Integer, ForeignKey("shop_stores.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopProductInventory(Base):
    __tablename__ = "shop_product_inventory"
    id = Column(Integer, primary_key=True)
    shop_product_id = Column(Integer, ForeignKey("shop_products.id"), nullable=False)
    shop_store_id = Column(Integer, ForeignKey("shop_stores.id"), nullable=False)
    quantity = Column(Integer, default=0)
    location_aisle = Column(String(50))
    location_shelf = Column(String(50))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopInventoryMovement(Base):
    __tablename__ = "shop_inventory_movements"
    id = Column(Integer, primary_key=True)
    shop_product_id = Column(Integer, ForeignKey("shop_products.id"), nullable=False)
    shop_store_id = Column(Integer, ForeignKey("shop_stores.id"), nullable=False)
    shop_product_inventory_id = Column(Integer, ForeignKey("shop_product_inventory.id"))
    quantity_change = Column(Integer, nullable=False)
    movement_type = Column(String(50), nullable=False)
    movement_status = Column(String(50), default='Completed')
    reference_id = Column(String(128))
    notes = Column(Text)
    performed_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopWishlist(Base):
    __tablename__ = "shop_wishlist"
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("app_users.id"), nullable=False)
    shop_product_id = Column(Integer, ForeignKey("shop_products.id"), nullable=False)
    added_date = Column(DateTime, default=datetime.utcnow)
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopProductVariantType(Base):
    __tablename__ = "shop_product_variant_types_master"
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False)
    description = Column(Text)
    display_sequence = Column(Integer)
    active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopProductVariantValue(Base):
    __tablename__ = "shop_product_variant_values_master"
    id = Column(Integer, primary_key=True)
    variant_type_id = Column(Integer, ForeignKey("shop_product_variant_types_master.id"), nullable=False)
    value = Column(String(256), nullable=False)
    display_sequence = Column(Integer)
    active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopProductVariant(Base):
    __tablename__ = "shop_product_variants"
    id = Column(Integer, primary_key=True)
    shop_product_id = Column(Integer, ForeignKey("shop_products.id"), nullable=False)
    variant_name = Column(String(256))
    variant_type_master_id = Column(Integer, ForeignKey("shop_product_variant_types_master.id"))
    variant_value_master_id = Column(Integer, ForeignKey("shop_product_variant_values_master.id"))
    sku = Column(String(256))
    price_adjustment = Column(DOUBLE_PRECISION, default=0)
    stock_quantity = Column(Integer, default=0)
    active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopShippingMethod(Base):
    __tablename__ = "shop_shipping_methods"
    id = Column(Integer, primary_key=True)
    name = Column(String(256), nullable=False)
    description = Column(Text)
    delivery_time = Column(String(128))
    shipping_cost = Column(DOUBLE_PRECISION)
    free_shipping_over = Column(DOUBLE_PRECISION)
    active = Column(Boolean, default=True)
    shop_store_id = Column(Integer, ForeignKey("shop_stores.id"))
    zone_id = Column(Integer)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopOrderShipment(Base):
    __tablename__ = "shop_order_shipments"
    id = Column(Integer, primary_key=True)
    shop_order_id = Column(Integer, ForeignKey("shop_orders.id"), nullable=False)
    shop_shipping_method_id = Column(Integer, ForeignKey("shop_shipping_methods.id"))
    tracking_number = Column(String(256))
    carrier = Column(String(128))
    shipment_status = Column(String(50), default='Preparing')
    shipped_date = Column(DateTime)
    estimated_delivery_date = Column(DateTime)
    actual_delivery_date = Column(DateTime)
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopProductComparison(Base):
    __tablename__ = "shop_product_comparisons"
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("app_users.id"), nullable=False)
    primary_product_id = Column(Integer, ForeignKey("shop_products.id"), nullable=False)
    compare_product_id = Column(Integer, ForeignKey("shop_products.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopStoreHours(Base):
    __tablename__ = "shop_store_hours"
    id = Column(Integer, primary_key=True)
    shop_store_id = Column(Integer, ForeignKey("shop_stores.id"), nullable=False)
    is_sunday_open = Column(Boolean, default=False)
    sunday_opening_time = Column(Time)
    sunday_closing_time = Column(Time)
    is_monday_open = Column(Boolean, default=True)
    monday_opening_time = Column(Time)
    monday_closing_time = Column(Time)
    is_tuesday_open = Column(Boolean, default=True)
    tuesday_opening_time = Column(Time)
    tuesday_closing_time = Column(Time)
    is_wednesday_open = Column(Boolean, default=True)
    wednesday_opening_time = Column(Time)
    wednesday_closing_time = Column(Time)
    is_thursday_open = Column(Boolean, default=True)
    thursday_opening_time = Column(Time)
    thursday_closing_time = Column(Time)
    is_friday_open = Column(Boolean, default=True)
    friday_opening_time = Column(Time)
    friday_closing_time = Column(Time)
    is_saturday_open = Column(Boolean, default=True)
    saturday_opening_time = Column(Time)
    saturday_closing_time = Column(Time)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopTaxRate(Base):
    __tablename__ = "shop_tax_rates"
    id = Column(Integer, primary_key=True)
    tax_name = Column(String(128), nullable=False)
    tax_rate_percentage = Column(DOUBLE_PRECISION, nullable=False)
    country = Column(String(128))
    state = Column(String(128))
    city = Column(String(128))
    zip_code = Column(String(50))
    zone_id = Column(Integer)
    active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ShopProductSupplier(Base):
    __tablename__ = "shop_product_suppliers"
    id = Column(Integer, primary_key=True)
    name = Column(String(512), nullable=False)
    contact_person = Column(String(256))
    company_name = Column(String(512))
    company_tax_id = Column(String(128))
    crm_company_id = Column(String(128))
    shop_store_id = Column(Integer, ForeignKey("shop_stores.id"))
    email = Column(String(256))
    phone = Column(String(50))
    address = Column(String(1024))
    city = Column(String(128))
    zip_code = Column(String(50))
    country = Column(String(128))
    website = Column(String(512))
    payment_terms = Column(String(256))
    notes = Column(Text)
    active = Column(Boolean, default=True)
    rating_score = Column(Integer)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
