from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, ForeignKey, UniqueConstraint, Numeric, Index, Date, BigInteger
from sqlalchemy.dialects.postgresql import JSONB, ARRAY
from datetime import datetime
from src.infrastructure.database import Base

class CRMCompanyType(Base):
    __tablename__ = "crm_master_company_types"
    id = Column(Integer, primary_key=True)
    name = Column(String(256), nullable=False)
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)

class CRMContactType(Base):
    __tablename__ = "crm_master_contact_types"
    id = Column(Integer, primary_key=True)
    name = Column(String(256), nullable=False)
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)

class CRMDocumentType(Base):
    __tablename__ = "crm_master_document_types"
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False, unique=True)
    description = Column(Text)
    file_extensions = Column(String(256))
    max_file_size_mb = Column(Integer)
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CRMCompany(Base):
    __tablename__ = "crm_companies"
    id = Column(Integer, primary_key=True)
    name = Column(String(512), nullable=False)
    trade_name = Column(String(512))
    brief_profile = Column(String(5000))
    full_profile = Column(Text)
    custom_number = Column(String(128))
    year_of_establishment = Column(Integer)
    industry = Column(String(256))
    market_cap = Column(Numeric(15, 2))
    number_of_employees = Column(Integer)
    annual_revenue = Column(Numeric(15, 2))
    full_address = Column(Text)
    address_line1 = Column(String(512))
    address_line2 = Column(String(512))
    city = Column(String(128))
    state = Column(String(128))
    country = Column(String(128))
    zip_code = Column(String(50))
    latitude = Column(Numeric(10, 8))
    longitude = Column(Numeric(11, 8))
    phone = Column(String(50))
    fax = Column(String(50))
    email = Column(String(256))
    website = Column(String(1024))
    ein_tax_id = Column(String(128))
    logo_url = Column(String(1024))
    facebook_url = Column(String(512))
    linkedin_url = Column(String(512))
    twitter_url = Column(String(512))
    is_verified = Column(Boolean, default=False)
    verified_at = Column(DateTime)
    is_active_or_archived = Column(Boolean, default=True)
    internal_ranking_score = Column(Integer)
    internal_remarks = Column(Text)
    company_snapshot_json = Column(JSONB)
    company_snapshot_json_url = Column(String(1024))
    snapshot_generated_at = Column(DateTime)
    company_profile_completion = Column(Integer)
    company_tags_completion = Column(Integer)
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CRMContact(Base):
    __tablename__ = "crm_contacts"
    id = Column(Integer, primary_key=True)
    first_name = Column(String(128), nullable=False)
    last_name = Column(String(128))
    date_of_birth = Column(Date)
    tax_id_or_ssn = Column(String(128))
    job_title = Column(String(256))
    company_name = Column(String(512))
    years_of_experience = Column(Integer)
    full_address = Column(String(1024))
    address_line1 = Column(String(512))
    address_line2 = Column(String(512))
    city = Column(String(128))
    state = Column(String(128))
    country = Column(String(128))
    zip_code = Column(String(50))
    mobile = Column(String(50))
    is_sms_subscribed = Column(Boolean, default=False)
    is_whatsapp_subscribed = Column(Boolean, default=False)
    personal_email = Column(String(256))
    personal_email_verified = Column(Boolean, default=False)
    personal_email_subscribed = Column(Boolean, default=True)
    business_email = Column(String(256))
    business_email_verified = Column(Boolean, default=False)
    business_email_subscribed = Column(Boolean, default=True)
    brief_profile = Column(String(5000))
    full_profile = Column(Text)
    public_profile_url = Column(String(512))
    internal_notes = Column(Text)
    facebook_url = Column(String(512))
    linkedin_url = Column(String(512))
    twitter_url = Column(String(512))
    is_verified = Column(Boolean, default=False)
    verified_at = Column(DateTime)
    is_active_or_archived = Column(Boolean, default=True)
    contact_ranking_score = Column(Integer)
    contact_snapshot_json = Column(JSONB)
    contact_snapshot_json_url = Column(String(1024))
    snapshot_generated_at = Column(DateTime)
    contact_profile_completion = Column(Integer)
    contact_tags_completion = Column(Integer)
    company_id = Column(Integer, ForeignKey("crm_companies.id"))
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CRMCompanyTag(Base):
    __tablename__ = "crm_company_tags"
    id = Column(Integer, primary_key=True)
    tag_title = Column(String(255), nullable=False)
    tag_description = Column(Text)
    rating_score = Column(Integer)
    display_sequence = Column(Integer)
    is_default_tag = Column(Boolean, default=False)
    company_id = Column(Integer, ForeignKey("crm_companies.id", ondelete="CASCADE"), nullable=False)
    master_tag_group_id = Column(Integer)
    master_tag_category_id = Column(Integer)
    master_tag_id = Column(Integer)
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CRMContactTag(Base):
    __tablename__ = "crm_contact_tags"
    id = Column(Integer, primary_key=True)
    tag_name = Column(String(255), nullable=False)
    tag_value = Column(Text)
    display_sequence = Column(Integer)
    rating_score = Column(Integer)
    is_default_tag = Column(Boolean, default=False)
    contact_id = Column(Integer, ForeignKey("crm_contacts.id", ondelete="CASCADE"), nullable=False)
    master_tag_group_id = Column(Integer)
    master_tag_category_id = Column(Integer)
    master_tag_id = Column(Integer)
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CRMCompanyContactMap(Base):
    __tablename__ = "crm_company_contact_maps"
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("crm_companies.id", ondelete="CASCADE"), nullable=False)
    contact_full_name = Column(String(256), nullable=False)
    job_title = Column(String(256))
    email = Column(String(256))
    phone = Column(String(50))
    is_primary_contact = Column(Boolean, default=False)
    display_sequence = Column(Integer)
    is_active = Column(Boolean, default=True)
    contact_id = Column(Integer, ForeignKey("crm_contacts.id", ondelete="CASCADE"), nullable=False)
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    __table_args__ = (
        UniqueConstraint('company_id', 'contact_id', name='uq_crm_company_contact_maps_company_contact'),
    )

class CRMAccountRepsTeam(Base):
    __tablename__ = "crm_account_reps_teams"
    id = Column(Integer, primary_key=True)
    is_primary_rep = Column(Boolean, default=False)
    role_type = Column(String(50))
    assignment_date = Column(Date, default=datetime.utcnow)
    is_active = Column(Boolean, default=True)
    user_id = Column(Integer, ForeignKey("app_users.id", ondelete="CASCADE"), nullable=False)
    company_id = Column(Integer, ForeignKey("crm_companies.id", ondelete="CASCADE"))
    contact_id = Column(Integer, ForeignKey("crm_contacts.id", ondelete="CASCADE"))
    assigned_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    __table_args__ = (
        UniqueConstraint('user_id', 'company_id', name='uq_crm_account_reps_teams_user_company'),
        UniqueConstraint('user_id', 'contact_id', name='uq_crm_account_reps_teams_user_contact'),
    )

class CRMBankInfo(Base):
    __tablename__ = "crm_bank_infos"
    id = Column(Integer, primary_key=True)
    bank_name = Column(String(256), nullable=False)
    account_number = Column(String(128))
    routing_number = Column(String(128))
    swift_code = Column(String(50))
    iban = Column(String(50))
    wire_account_number = Column(String(128))
    account_type = Column(String(50))
    account_holder_name = Column(String(256))
    bank_address = Column(String(512))
    bank_city = Column(String(128))
    bank_state = Column(String(128))
    bank_country = Column(String(128))
    account_phone = Column(String(50))
    account_email = Column(String(256))
    is_verified = Column(Boolean, default=False)
    verified_at = Column(DateTime)
    is_active = Column(Boolean, default=True)
    notes = Column(Text)
    contact_id = Column(Integer, ForeignKey("crm_contacts.id", ondelete="CASCADE"))
    company_id = Column(Integer, ForeignKey("crm_companies.id", ondelete="CASCADE"))
    institute_id = Column(Integer)
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CRMDocument(Base):
    __tablename__ = "crm_documents"
    id = Column(Integer, primary_key=True)
    document_title = Column(String(512), nullable=False)
    file_name = Column(String(512))
    file_url = Column(String(1024), nullable=False)
    file_size_bytes = Column(BigInteger)
    file_extension = Column(String(20))
    mime_type = Column(String(100))
    description = Column(Text)
    is_public = Column(Boolean, default=False)
    crm_master_document_type_id = Column(Integer, ForeignKey("crm_master_document_types.id"))
    user_id = Column(Integer, ForeignKey("app_users.id"))
    company_id = Column(Integer, ForeignKey("crm_companies.id", ondelete="CASCADE"))
    contact_id = Column(Integer, ForeignKey("crm_contacts.id", ondelete="CASCADE"))
    uploaded_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CRMNote(Base):
    __tablename__ = "crm_notes"
    id = Column(Integer, primary_key=True)
    title = Column(String(256))
    notes = Column(Text, nullable=False)
    note_type = Column(String(50), default='general')
    is_pinned = Column(Boolean, default=False)
    is_private = Column(Boolean, default=False)
    company_id = Column(Integer, ForeignKey("crm_companies.id", ondelete="CASCADE"))
    contact_id = Column(Integer, ForeignKey("crm_contacts.id", ondelete="CASCADE"))
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CRMGroup(Base):
    __tablename__ = "crm_groups"
    id = Column(Integer, primary_key=True)
    name = Column(String(256), nullable=False)
    description = Column(Text)
    group_type = Column(String(100))
    is_active = Column(Boolean, default=True)
    member_count = Column(Integer, default=0)
    max_members = Column(Integer)
    is_public = Column(Boolean, default=False)
    auto_sync = Column(Boolean, default=False)
    sync_criteria = Column(JSONB)
    created_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class CRMGroupMember(Base):
    __tablename__ = "crm_group_members"
    id = Column(Integer, primary_key=True)
    member_name = Column(String(256), nullable=False)
    member_email = Column(String(256))
    member_phone = Column(String(50))
    can_receive_messages = Column(Boolean, default=True)
    can_send_messages = Column(Boolean, default=False)
    is_admin = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)
    joined_at = Column(DateTime, default=datetime.utcnow)
    removed_at = Column(DateTime)
    group_id = Column(Integer, ForeignKey("crm_groups.id", ondelete="CASCADE"), nullable=False)
    contact_id = Column(Integer, ForeignKey("crm_contacts.id", ondelete="CASCADE"))
    user_id = Column(Integer, ForeignKey("app_users.id", ondelete="CASCADE"))
    added_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    __table_args__ = (
        UniqueConstraint('group_id', 'contact_id', name='uq_crm_group_members_group_contact'),
        UniqueConstraint('group_id', 'user_id', name='uq_crm_group_members_group_user'),
    )

class CRMGroupMessage(Base):
    __tablename__ = "crm_group_messages"
    id = Column(Integer, primary_key=True)
    subject = Column(String(512))
    body = Column(Text, nullable=False)
    message_type = Column(String(50), default='broadcast')
    status = Column(String(50), default='pending')
    sent_at = Column(DateTime)
    scheduled_for = Column(DateTime)
    has_attachments = Column(Boolean, default=False)
    attachments = Column(JSONB)
    total_recipients = Column(Integer, default=0)
    delivered_count = Column(Integer, default=0)
    viewed_count = Column(Integer, default=0)
    clicked_count = Column(Integer, default=0)
    group_id = Column(Integer, ForeignKey("crm_groups.id", ondelete="CASCADE"), nullable=False)
    from_group_member_id = Column(Integer, ForeignKey("crm_group_members.id"))
    template_id = Column(Integer)
    sent_by_user_id = Column(Integer, ForeignKey("app_users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
